version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=graphsql"
    ports:
      - "3306:3306"
volumes:
  mysqldata: